import hmac
import streamlit as st


def check_password():
    """Returns `True` if the user had a correct password."""

    def login_form():
        """Form with widgets to collect user information"""
        with st.form("Credentials"):
            st.text_input("Username", key="username")
            st.text_input("Password", type="password", key="password")
            st.form_submit_button("Log in", on_click=password_entered)

    def password_entered():
        """Checks whether a password entered by the user is correct."""
        if st.session_state["username"] in st.secrets[
            "passwords"
        ] and hmac.compare_digest(
            st.session_state["password"],
            st.secrets.passwords[st.session_state["username"]],
        ):
            st.session_state["password_correct"] = True
            del st.session_state["password"]  # Don't store the username or password.
            del st.session_state["username"]
        else:
            st.session_state["password_correct"] = False

    # Return True if the username + password is validated.
    if st.session_state.get("password_correct", False):
        return True

    # Show inputs for username + password.
    login_form()
    if "password_correct" in st.session_state:
        st.error("😕 User not known or password incorrect")
    return False


if not check_password():
    st.stop()

#Text to image
'''
create a streamlit app which allows user to enter a text and then calls a function after button is clicked. this function give the name get_image_openai()
in the function use open ai dalle2 model for generating image from text
i have two files 
main.py - with streamlit code
call_openai.py - for function call

https://platform.openai.com/docs/guides/images
'''
import streamlit as st
from services.call_openai import get_image_openai

# Streamlit app interface
st.title("DALL·E Image Generator")

# Text input for user to describe the image
user_input = st.text_input("Enter a description for the image:")

# Button to trigger image generation
if st.button("Generate Image"):
    if user_input:
        st.write("Generating image...")

        # Call the function to generate image
        image_url = get_image_openai(user_input)

        # Display the image if it's successfully generated
        if image_url:
            st.image(image_url, caption="Generated by DALL·E", use_column_width=True)
        else:
            st.write("Failed to generate image. Please try again.")
    else:
        st.warning("Please enter a description.")
